<a href="https://colab.research.google.com/github/vedhasrinammi-debug/NAMMI-VEDHA-SRI/blob/main/assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Example A1 — The Comparison**
Your marks in 5 subjects this semester vs the previous semester.
Your code must answer:
(i) Which array has a higher average and by exactly how much?
(ii) How many times does the first value exceed the second value in the same position?
(iii) What is the gap between the maximum values of the two arrays?

In [4]:
import numpy as np

a = np.array([85, 92, 78, 88, 95])
b = np.array([82, 94, 75, 80, 91])
print("(i) This semester is higher by:", np.mean(a) - np.mean(b))
print("(ii) Times exceeded:", np.sum(a > b))
print("(iii) Max gap:", np.max(a) - np.max(b))

(i) This semester is higher by: 3.1999999999999886
(ii) Times exceeded: 4
(iii) Max gap: 1


**Example A2 — The Trend Finder**
Your daily study hours for the past 2 weeks.
Your code must answer:
(i) Was the overall trend increasing or decreasing? Show this numerically.
(ii) What was the range — the difference between peak and lowest value?
(iii) How many periods were above the overall average?

In [6]:
import numpy as np
hours = np.array([4, 5, 4, 6, 5, 7, 6, 7, 8, 7, 8, 9, 8, 9])
print("Trend:", hours[-1] - hours[0])
print("Range:", np.max(hours) - np.min(hours))
print("Days above average:", np.sum(hours > np.mean(hours)))

Trend: 5
Range: 5
Days above average: 8


**Example A3 — The Filter**
Points scored by 10 players in a game or sport you follow.
Your code must answer:
(i) How many values exceed the average of the array?
(ii) List only the values that satisfy your defined condition.
(iii) What percentage of the total does the filtered group represent?

In [2]:
import numpy as np

points = np.array([12, 25, 8, 19, 30, 15, 22, 14, 5, 28])
print("(i) Above average:", np.sum(points > np.mean(points)))
f = points[points >= 20]
print("(ii) Filtered:", f)
print("(iii) Percentage:", (np.sum(f) / np.sum(points)) * 100)

(i) Above average: 5
(ii) Filtered: [25 30 22 28]
(iii) Percentage: 58.98876404494382


**Example B1 — The Reservation System**

Project topic slots open for student selection.
Your code must answer:
(i) How many slots remain available after your updates?
(ii) What percentage of capacity has been utilised?
(iii) Is the system more than 60 percent full? Print a clear statement.

In [4]:
import numpy as np
seats = np.zeros(20)
seats[[1, 3, 4, 7, 8, 11, 12, 14, 15, 17, 18, 19]] = 1
print("(i) Available:", np.sum(seats == 0))
pct = (np.sum(seats) / seats.size) * 100
print("(ii) Utilised:", pct, "%")
print("(iii) System > 60% full:", pct > 60)

(i) Available: 8
(ii) Utilised: 60.0 %
(iii) System > 60% full: False


**Example B2 — The Tracker That Starts Fresh**

Points earned per round in a 10-round game or quiz.
Your code must answer:
(i) What is the current cumulative total of recorded values?
(ii) How many entries are still at zero (not yet recorded)?
(iii) If your target was a fixed value, how far are you from it?

In [5]:
import numpy as np
scores = np.zeros(10)
scores[:6] = [12, 15, 8, 14, 10, 11]
print("(i) Total:", np.sum(scores))
print("(ii) At zero:", np.sum(scores == 0))
print("(iii) Gap to target:", 100 - np.sum(scores))

(i) Total: 70.0
(ii) At zero: 4
(iii) Gap to target: 30.0


**Example B3 — The Scoreboard with Strategy**

Number of questions answered correctly by 8 students in a quiz.
Your code must answer:
(i) Who or what is leading and by what margin over the last place?
(ii) Are any entities still at zero? What does that mean in your context?
(iii) What is the average score across all entities?

In [7]:
import numpy as np
scores = np.zeros(8)
scores[:] = [15, 18, 0, 12, 20, 14, 0, 16]
print("(i) Top score:", np.max(scores), "| Margin over last:", np.max(scores) - np.min(scores))
print("(ii) Students at zero:", np.sum(scores == 0))
print("(iii) Average:", np.mean(scores))

(i) Top score: 20.0 | Margin over last: 20.0
(ii) Students at zero: 2
(iii) Average: 11.875


**Example C1 — The Discount System**
End-of-season clearance with varying markdown percentages.
Your code must answer:
(i) What is the total revenue at full price compared to after discounts?
(ii) Which product offers the best deal in absolute terms?
(iii) What percentage of revenue is lost due to discounts?

In [8]:
import numpy as np

prices = np.array([100, 200, 150, 80, 120, 300, 50, 250])
multipliers = np.zeros(8) + 1.0
multipliers[2:5] = 0.7
multipliers[5:] = 0.5
discounted = prices * multipliers
print("(i) Full revenue:", np.sum(prices), "| Discounted:", np.sum(discounted))
print("(ii) Max discount savings:", np.max(prices - discounted))
print("(iii) Revenue lost percentage:", ((np.sum(prices) - np.sum(discounted)) / np.sum(prices)) * 100)

(i) Full revenue: 1250 | Discounted: 845.0
(ii) Max discount savings: 150.0
(iii) Revenue lost percentage: 32.4


**Example C2 — The Grading Weight System**
Design your own weighting scheme for your current semester subjects.
Your code must answer:
(i) How does the weighted average differ from the simple unweighted average?
(ii) Which student benefits most from the weighting? Which is disadvantaged?
(iii) By how many marks does the weighted score differ from simple average for each student?

In [9]:
import numpy as np
marks = np.array([[85, 90, 75, 80, 95],[70, 80, 90, 75, 85]])
weights = np.zeros(5) + 1.0
weights[0] = 1.5
weights[4] = 2.0
unweighted_avg = np.mean(marks, axis=1)
weighted_avg = np.average(marks, axis=1, weights=weights)
diff = weighted_avg - unweighted_avg
print("(i) Group average difference:", np.mean(weighted_avg) - np.mean(unweighted_avg))
print("(ii) Benefited student index:", np.argmax(diff), "| Disadvantaged student index:", np.argmin(diff))
print("(iii) Individual differences:", diff)


(i) Group average difference: 0.7692307692307736
(ii) Benefited student index: 0 | Disadvantaged student index: 1
(iii) Individual differences: [1.53846154 0.        ]


**Example C3 — The Performance Multiplier**

6 delivery agents on base pay with efficiency multipliers.
Your code must answer:
(i) What is the final range between highest and lowest performer?
(ii) What is the average multiplier applied across the group?
(iii) How many performers are above the group average after multipliers?

In [10]:
import numpy as np
base_pay = 500
m = np.zeros(6) + 1.0
m[0] = 1.4
m[1] = 1.2
m[4] = 0.8

final_pay = base_pay * m
print("(i) Final pay range:", np.max(final_pay) - np.min(final_pay))
print("(ii) Average multiplier:", np.mean(m))
print("(iii) Performers above average:", np.sum(final_pay > np.mean(final_pay)))

(i) Final pay range: 300.0
(ii) Average multiplier: 1.0666666666666667
(iii) Performers above average: 2


**Example D1 — The Survey Simulator**

Number of online courses enrolled this semester (40 students, range 0 to 6).Your code must answer:
(i) What is the simulated population average for this variable?
(ii) Define a healthy or acceptable range. What percentage falls within it?
(iii) What is the most extreme 10 percent doing (above 90th percentile)?

In [12]:
import numpy as np
hours = np.array([12, 25, 32,  8, 15, 20, 28, 35, 10, 18,
                  14, 22, 30,  6, 17, 24, 29, 33, 11, 19,
                  13, 21, 31,  7, 16, 23, 27, 34,  9, 26,
                  15, 20, 25, 30, 12, 18, 22,  5, 33, 28])
print("(i) Average study hours:", np.mean(hours))
healthy = hours[(hours >= 15) & (hours <= 30)]
print("(ii) Acceptable range %:", (healthy.size / hours.size) * 100)
print("(iii) Top 10% studious values:", hours[hours > np.percentile(hours, 90)])


(i) Average study hours: 20.575
(ii) Acceptable range %: 57.49999999999999
(iii) Top 10% studious values: [35 33 34 33]


**Example D2 — The Business Simulator**
Calls received per hour at a student helpline for 8 hours.
Your code must answer:
(i) What are the peak and off-peak periods in the simulation?
(ii) What is the projected monthly or weekly total?
(iii) On what percentage of periods does performance exceed your defined target?

In [13]:
import numpy as np
sales = np.array([55, 62, 48, 70, 85, 90, 42, 58, 67, 72, 88, 95, 50, 61, 64,
                  78, 92, 99, 45, 53, 66, 74, 89, 91, 40, 57, 69, 75, 87, 96])
print("(i) Peak sales:", np.max(sales), "| Off-peak sales:", np.min(sales))
print("(ii) Projected weekly sales:", np.mean(sales) * 7)
print("(iii) Days exceeding target %:", np.mean(sales > 70) * 100)

(i) Peak sales: 99 | Off-peak sales: 40
(ii) Projected weekly sales: 494.19999999999993
(iii) Days exceeding target %: 46.666666666666664


**Example D3 — The What-If Explorer**

What happens when you simulate 10,000 flips instead?
Your code must answer:
(i) What did your simulation predict for the defined question?
(ii) Run the simulation twice with different seeds. How much does the answer vary?
(iii) Write a one-line comment in your code stating your conclusion.

In [14]:
import numpy as np
def run_sim(seed_value):
    np.random.seed(seed_value)
    dice1 = np.random.randint(1, 7, 10000)
    dice2 = np.random.randint(1, 7, 10000)
    sums = dice1 + dice2
    successes = np.sum((sums == 7) | (sums == 11))
    return successes / 10000
prob_seed1 = run_sim(42)
prob_seed2 = run_sim(123)
print(f"(i) Predicted probability (Seed 42): {prob_seed1 * 100:.2f}%")
variance = abs(prob_seed1 - prob_seed2) * 100
print(f"(ii) Probability with Seed 123: {prob_seed2 * 100:.2f}% | Absolute variance: {variance:.2f}%")


(i) Predicted probability (Seed 42): 21.72%
(ii) Probability with Seed 123: 22.07% | Absolute variance: 0.35%


**Example E1 — Something You Measured This Week**

Amount of water consumed per day this week (in glasses or litres).

In [17]:
import numpy as np
sleep_hours = np.array([7.2, 6.5, 7.8, 6.0, 7.1, 8.2, 6.8])
print("Total sleep logged:", np.sum(sleep_hours), "hours")
print("Average nightly sleep:", np.mean(sleep_hours), "hours")
print("Shortest sleep session:", np.min(sleep_hours), "hours")
print("Longest sleep session:", np.max(sleep_hours), "hours")

Total sleep logged: 49.599999999999994 hours
Average nightly sleep: 7.0857142857142845 hours
Shortest sleep session: 6.0 hours
Longest sleep session: 8.2 hours


**Example E2 — Something You Follow**

Your favourite YouTuber's video view counts for last 7 uploads

In [18]:
import numpy as np
views = np.array([142.0, 196.0, 115.0, 108.0, 80.2, 71.0, 53.1])
print("(i) Total:", np.sum(views), "million")
print("(ii) Zeros:", np.sum(views == 0))
print("(iii) Gap to target:", 1000 - np.sum(views), "million")

(i) Total: 765.3000000000001 million
(ii) Zeros: 0
(iii) Gap to target: 234.69999999999993 million


**Example E3 — Something That Surprised You.  **

Step 1: Create an array of real data (at least 8 values)
Step 2: Before running any analysis, write a comment predicting what you expect to find
Step 3: Run your analysis
Step 4: Write a final comment stating whether your prediction was correct
and what, if anything, surprised you about the actual result.

In [19]:
import numpy as np
study_hours = np.array([12.5, 8.0, 15.0, 5.5, 22.0, 14.5, 9.0, 18.5])
avg_hours = np.mean(study_hours)
max_hours = np.max(study_hours)
print("Average study hours:", avg_hours)
print("Maximum study hours:", max_hours)

Average study hours: 13.125
Maximum study hours: 22.0


**Example F1 — The No-Change Proof**

Take any 3x3 or 4x4 matrix of real data — marks, prices, distances, or any other numeric dataset. Multiply it by the identity matrix using np.dot(). Verify the result equals the original using np.allclose() or
np.array_equal().
Your code must answer:
(i) Does A × I equal A? Verify this programmatically.
(ii) Does I × A also equal A? Show both directions.
(iii) Write a comment explaining when you would use this check in a real program


In [21]:
import numpy as np
A = np.array([[85, 90, 78],
              [72, 88, 91],
              [89, 76, 84]])
I = np.eye(3)
result1 = np.dot(A, I)
print("A × I equals A?", np.array_equal(result1, A))
result2 = np.dot(I, A)
print("I × A equals A?", np.array_equal(result2, A))

A × I equals A? True
I × A equals A? True


**Example F2 — The Transformation Starting Point**
A product matrix where identity = no seasonal adjustment applied yet.
Your code must answer:
(i) Show the result before applying the modification.
(ii) Apply one meaningful change and show the result after.
(iii) Interpret the change in one comment line in plain English.

In [26]:
import numpy as np
sales = np.array([[100, 150, 200],

                  [90,  130, 170]])
modifier = np.eye(3)
print("(i) Before adjustment:\n", np.dot(sales, modifier))
modifier[2, 2] = 1.20
print("\n(ii) After adjustment:\n", np.dot(sales, modifier))


(i) Before adjustment:
 [[100. 150. 200.]
 [ 90. 130. 170.]]

(ii) After adjustment:
 [[100. 150. 240.]
 [ 90. 130. 204.]]


**Example F3 — The Pattern Discovery**

Create identity matrices of size 2, 3, 4, and 5. For each one, compute its trace using np.trace() and its
determinant using np.linalg.det(). Record all results and identify the pattern.
Your code must answer:
(i) What is the trace of each identity matrix? State the pattern as a comment.
(ii) What is the determinant of each identity matrix? State the pattern.
(iii) Based on these two patterns, write a general rule for identity matrices in a comment.

In [27]:
import numpy as np

# (i) & (ii) Compute Trace and Determinant
print("2x2:", np.trace(np.eye(2)), np.linalg.det(np.eye(2)))
print("3x3:", np.trace(np.eye(3)), np.linalg.det(np.eye(3)))
print("4x4:", np.trace(np.eye(4)), np.linalg.det(np.eye(4)))
print("5x5:", np.trace(np.eye(5)), np.linalg.det(np.eye(5)))

2x2: 2.0 1.0
3x3: 3.0 1.0
4x4: 4.0 1.0
5x5: 5.0 1.0


**Example G1 — The Scale Builder**
Fuel efficiency scale from 5 kmpl to 30 kmpl in steps of 2.5
Your code must answer:
(i) Apply at least 5 real or realistic measurements to your scale.
(ii) Classify each measurement into a zone you define (e.g., low, medium, high).
(iii) What percentage of measurements fall in each zone?

In [28]:
import numpy as np
scale = np.arange(5, 31, 2.5)
cars = np.array([6.2, 14.5, 28.0, 19.8, 11.0])
low = cars[cars < 12]
med = cars[(cars >= 12) & (cars <= 22)]
high = cars[cars > 22]
print("(i) Cars:", cars)
print("(ii) Low:", low, "| Med:", med, "| High:", high)
print("(iii) Low %:", (low.size / cars.size) * 100)
print("      Med %:", (med.size / cars.size) * 100)
print("      High %:", (high.size / cars.size) * 100)


(i) Cars: [ 6.2 14.5 28.  19.8 11. ]
(ii) Low: [ 6.2 11. ] | Med: [14.5 19.8] | High: [28.]
(iii) Low %: 40.0
      Med %: 40.0
      High %: 20.0


**Example G2 — The Schedule Generator**

Meeting slots in a working day from 9 AM to 5 PM every 45 minutes.
Your code must answer:
(i) How many total slots are generated?
(ii) Which slot number is closest to noon or midpoint of the schedule?
(iii) If 3 slots are cancelled, how many remain and what is the new utilisation rate?

In [29]:
import numpy as np
slots = np.arange(540, 1021, 45)
total = slots.size
print("(i) Total slots:", total)
print("(ii) Slot closest to noon index:", np.argmin(np.abs(slots - 720)))
remaining = total - 3
print("(iii) Remaining slots:", remaining, "| Utilisation:", (remaining / total) * 100, "%")


(i) Total slots: 11
(ii) Slot closest to noon index: 4
(iii) Remaining slots: 8 | Utilisation: 72.72727272727273 %


**Example G3 — The Discovery**
At what distance does travel time at 60 kmph save more than 1 hour vs 40 kmph?
Your code must answer:
(i) Identify the exact threshold or crossover point from the array.
(ii) State your finding as a one-line conclusion written as a code comment.
(iii) Write which function (arange or linspace) you used and why in a comment.

In [30]:
import numpy as np
distances = np.arange(10, 201, 10)
time_40 = distances / 40
time_60 = distances / 60
time_saved = time_40 - time_60
threshold_distance = distances[time_saved > 1][0]
print("(i) Threshold crossover distance:", threshold_distance, "km")

# (ii) Conclusion: Traveling at 60 kmph saves more than 1 hour compared to 40 kmph once the distance exceeds 120 km.
# (iii) Selection: Used 'arange' to define the sequence by a specific, easy-to-read step size of 10 km intervals.


(i) Threshold crossover distance: 130 km
